### ISSUE TITLE
XLRD does not support XLSX files

### ISSUE THREAD

**Issue by ronaldvdv** [Gurobi/modeling-examples#12]
Example https://github.com/Gurobi/modeling-examples/tree/master/technician_routing_scheduling uses the `xlrd` package. Unfortunately this package [does not support](https://pypi.org/project/xlrd/) reading XLSX files anymore. This may apply to other examples as well.

**Comment by Marika-K** [comment]
Changed from xlrd to pandas to read excel files. The notebook should work again.
