### ISSUE TITLE
curve_fitting notebook incorrect dependent/independent variable definition

### ISSUE THREAD

**Issue by gokhanceyhan** [Gurobi/modeling-examples#2]
Referring to this notebook: https://gurobi.github.io/modeling-examples/curve_fitting/curve_fitting.html

x should be the **independent** variable and y should be the **dependent** variable based on the equation y = ax + b.

**Comment by Panitzin** [comment]
Thank you very much for the feedback, we have corrected the typo.
Regards, Pano
