### ISSUE TITLE
How Indicator constraint can be triggered with multiple variables in Gurobi?

### ISSUE THREAD

**Issue by ptkphung99** [Gurobi/modeling-examples#8]
Dear Sir/Madam,

I am trying to write the constraint related to multiple variables. However, it shows error "Indicator constraints can only be triggered by a single binary variable at a given value". Can you help me fix this error? Thank you very much!
The code is following:
mdl.addConstrs((x[i,j,k] - t[i,j,k] == 1) >> (d2[j,k] == d2[i,k] - d[i,j]) for i, j, k in arcos2 if i != 0 and j != 0)

Where: 
- x[i,j,k], t[i,j,k] are binary variables
- d2[j,k], d2[i,k] are continuous variables
- d[i,j] is a parameter

**Comment by gglockner** [comment]
This doesn't look like an issue with the modeling code in this Github repository. For assistance, please go to https://support.gurobi.com and post your question to the community forum; if you are a commercial customer, you can also go there to open a support ticket.
